### PR TITLE
update guide.coffee

### PR DESCRIPTION
**Pull request by jwidness**
Descriptions were modified for a bunch of animals, "sometimes confused with" was added to each animal.  Climbing description was added.

I talked to Mimi and she approved the changes to the field guide.

### CODE REVIEW

**Comment by srallen** [comment]
@jwidness, is the "Sometimes confused with..." line intended to be a new paragraph?  Right now, the code is inserting the `description` into a paragraph tag, but I may change that to be a `<div>` and add appropriate `<p>` tags in the description string. I can do that after I merge in though, unless you'd like to tackle that? FYI, as it is now, it doesn't render "Sometimes confused with..." into a new paragraph, it's a part of the rest of the content as one paragraph block.

**Comment by jwidness** [comment]
Oops, I did another commit before I saw your second comment.  I sort of intended for the "sometimes confused with" part to be a new paragraph, but whatever looks good is fine with me.  I don't really have any way to run it, so sorry for submitting buggy code :/

Linking to the other field guide entries is a great idea!  I couldn't tell if you're offering to do that or not, but I don't think I have the time to do it right now.

**Comment by srallen** [comment]
No worries, that's why we check with the pull requests :)

I can handle the markup changes and adding the links. I'll prioritize this since I'll be out for Thanksgiving the rest of the week, so it should be deployed later on today.

**Comment by jwidness** [comment]
Awesome! Thanks!

**Pull request merged**
